<?php
/**
 * Gladiatorz ist ein Browsergame
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 *
 * Verbatim copying and distribution of this entire article is permitted in any medium without royalty provided this notice is preserved. 
 * 
 * @link http://www.gladiatorgame.de
 * @version 0.9
 * @copyright Copyright: 2009-2011 Patrick Schön
 * @author Patrick Schön <info@cyberrranger.com>
 */

$Select = array();
$Select['OnOff'] = '<option>An</option><option>Aus</option>';

$Help = array();
$Help['Kampfuebersicht'] = 'op';
$Help['Kampfbericht'] = 'op';
$Help['Tipps'] = 'op';
$Help['Werbung'] = 'op';
$Help['Schriftgroesse'] = 'op';
$Help['Schriftart'] = 'op';

$eigenschaften = array("staerke","geschick","kondition","charisma","inteligenz");
$eigenschaften_text = array("Stärke","Geschick","Kondition","Charisma","Intelligenz");

$ueigenschaften = array("Schlagkraft","Einstecken","Kraftprotz","Glueck","Sammler");
$ueigenschaften_text = array("Schlagkraft","Einstecken","Kraftprotz","Glueck","Sammler");

$faehigkeiten = array("waffenkunde","ausweichen","taktik","zweiwaffenkampf","heilkunde","schildkunde");
$faehigkeiten_text = array("Waffenkunde","Ausweichen","Taktik","2-Waffenkampf","Heilkunde","Schildkunde");

$moves = array("kraftschlag","wutschrei","armor","kritischer_schlag","wundhieb","kraftschrei","block","taeuschen","koerperteil_abschlagen","sand_werfen","ausweichen","todesschlag","konter","berserker","anti_def");
$moves_text = array("Kraftschlag","Wutschrei","Schutz","Kritischer Schlag","Wuchtschlag","Kraftschrei","Block","Täschen","Körperteil abschlagen","Sand werfen","Ausweichen","Todesschlag","Konter","Berserker","Anti Deff");

$Tooltips = array();
$Tooltips['TT_PowMod'] = 'PowMod benötigst du um zu kämpfen. Hier siehst du deine aktuellen PowMod.';
$Tooltips['TT_Kraft'] = 'Deine Kraft ist wichtig, um im Kampf zu Überleben. Hier siehst du deine aktuellen Kraftreserven.';
$Tooltips['TT_Gold'] = 'Um deinen Charakter zu entwicklen, benötigst du Gold. Hier siehst du deinen aktuellen Goldschatz.';
$Tooltips['TT_Logout'] = 'Hier kannst du dich aus dem Spiel ausloggen; hast du dich schon schlafen gelegt?!';
$Tooltips['TT_Spieler_online'] = '<font color=green><strong>'.showOnlinePlayer().'</strong></font>';
$Tooltips['TT_Posteingang'] = 'Deine neuen Nachrichten.<br /><strong>('.$Messages[0].' Neue!)</strong>';
$Tooltips['TT_Postausgang'] = 'Von dir verschickte Nachrichten.';
$Tooltips['TT_Neue_Nachricht'] = 'Hier kannst du neue Nachrichten verfassen.';
$Tooltips['TT_PowMod_Anzeige'] = 'Die grafische Anzeige deiner PowMod.';
$Tooltips['TT_Kraft_Anzeige'] = 'Die grafische Anzeige deiner Kraft.';
$Tooltips['TT_Heilerbutton'] = 'Das tut gut! Durch Klick auf diesen Button kannst du dich für 300 Gold vollständig heilen lassen.';
$Tooltips['TT_EXP_Anzeige'] = 'Die grafische Anzeige deiner Erfahrungspunkte. Wenn die Leiste voll ist, steigst du um ein Level auf.';
$Tooltips['TT_EXP_Fortschritt'] = '<strong>'.$User['exp'].'/'.neededEXP($User['level']).' EXP</strong>';
$Tooltips['TT_Level_Anzeige'] = 'Hier steht dein aktuelles Level.';

if($Settings['tooltips'] > 1)
{
	$Tooltips['TT_Uebersicht'] = 'Auf der Übersicht findest du alles, was du nach dem Login benötigst. Informationen zu Neuerungen im Spiel oder die Votebuttons, die du jeden Tag benutzen solltest.';
	$Tooltips['TT_Charakter'] = 'Im Charakterbildschirm findest du eine hilfreiche Zusammenfassung deiner Eigenschaften und Ausrüstung.';
	$Tooltips['TT_Inventar'] = 'Im Inventar kannst du deine Items ausrüsten, verkaufen oder versteigern.';
	$Tooltips['TT_Tiergrube'] = 'In der Tiergrube begegnest du den gefürchtetsten Wesen der Arena. Hier verdienen sich alle Gladiatoren Gold, Ruhm und Ehre.';
	$Tooltips['TT_Rangkaempfe'] = 'In der Rangkampf-Arena kannst du dich mit anderen Spielern deines Levels messen, um zu beweisen, dass du allein der beste Gladiator bist!';
	$Tooltips['TT_Arena'] = 'In der Arena stehen sich die Gladiatoren im harten Kampf - Mann gegen Mann - gegenüber. Wer hier nicht aufpasst wird schnell erschlagen.';
	$Tooltips['TT_Prestigekaempfe'] = 'In der Prestigekampf-Arena kannst du gegen ganze Tierrudel antreten, um dir Ansehen und die hoch geschützten Medaillen zu verdienen!';
	$Tooltips['TT_Duelle'] = 'In der Duell-Arena kannst du gegen ausgewählte Gegner kämpfen oder auf Kämpfe anderer Gladiatoren wetten.';
	$Tooltips['TT_Schmiede'] = 'Die Schmiede kann dir alle Ausrüstungswünsche erfüllen, so lange du genug Gold mitbringst. Artefakte findest du hier allerdings nicht.';
	$Tooltips['TT_Schulen'] = 'Die Schulen sind Zusammenschlüsse von wagemutigen Gladiatoren mit gleichen Zielen. Schulen bieten dir wertvolle Boni, daher solltest du zeitig einer Gemeinschaft beitreten.';
	$Tooltips['TT_Gasthaus'] = 'Im Gasthaus kannst du dich ausruhen und schlafen um deine Lebensenergie und deinen PowMod wieder herzustellen.';
	$Tooltips['TT_Basar'] = 'Auf dem Basar findest du viele neue Items, die deinen Charakter aufwerten. Nur hier kannst du begehrte Artefakte käuflich erwerben.';
	$Tooltips['TT_Trainer'] = 'Der Trainer hilft dir, deinen Körper und Geist nach deinen Wünschen zu formen. Natürlich gegen entsprechende Bezahlung, versteht sich...';
	$Tooltips['TT_Forum'] = 'Im Forum kannst du Neuerungen nachlesen, dich mit anderen Gladitoren unterhalten oder deinen Schulengladiatoren eine Nachricht hinterlassen. Du solltest mindestens einmal in der Woche ins Forum schauen!';
	$Tooltips['TT_Medaillen'] = 'In der Medaillenübersicht kannst du deine gewonnenen, sowie gekauften Medaillen verwalten und dir tolle Boni freischalten lassen.';
	$Tooltips['TT_Suche'] = 'Die mächtige Suchfunktion hilft dir dabei, nach den unterschiedlichsten Dingen und Spielern zu suchen. Dafür benötigst du nur wenige Klicks.';
	$Tooltips['TT_Highscore'] = 'Wenn du wissen willst, welcher Gladiator die meisten Punkte hat oder wo du in der Rangliste stehst, solltest du einen Blick in die Highscore wagen.';
	$Tooltips['TT_Hilfe'] = 'Wenn du etwas im Spiel nicht verstehst oder eine Frage hast, kannst du im Gladiatorz-Wiki nützliche Informationen finden und aktiv am Erfolg des Wiki mitarbeiten.';
	$Tooltips['TT_Statistiken'] = 'Die Statistiken geben unter anderem Auskunft darüber, wie viele Gladiatoren den Kampf aufgenommen haben und in den letzten Tagen online waren.';
	$Tooltips['TT_Arenaleitung'] = 'Hier verbergen sich die Gelehrten der Gladiatorenarenen, vielleicht haben Sie ja einen Job für dich?';
	$Tooltips['TT_Hall_of_Fame'] = 'Hier findest du berühmte Imperatoren aus vergangenen Zeiten, die uns immer in Erinnerung bleiben.';
	$Tooltips['TT_Haendler'] = 'Hier kannst du kaufen, kaufen kaufen.';
	$Tooltips['TT_Tunier'] = 'Melde dich zu einem Tunier an.';
	$Tooltips['TT_Move'] = 'Skill deine Moves';
	$Tooltips['TT_challenge'] = 'Herausforderungen';
	
}

$Vorname = array(
"Achaicus",
"Aemilianus",
"Afer",
"Africanus",
"Agrippa",
"Ahenobarbus",
"Albinus",
"Allobrigicus",
"Arvina",
"Asiaticus",
"Asina",
"Baliaricus",
"Barbula",
"Blaesus",
"Blasio",
"Brutus",
"Buteo",
"Caecus",
"Caepio",
"Caesar",
"Caesoninus",
"Caiatinus",
"Calvus",
"Calvus",
"Canina",
"Carbo",
"Catalina",
"Cato",
"Catulus",
"Caudex",
"Caudinus",
"Celer",
"Censorinus",
"Centumalus",
"Cerco",
"Cethegus",
"Cicero",
"Cinna",
"Clepsina",
"Clodianus",
"Corculum",
"Corvus",
"Cotta",
"Crassus",
"Creticus",
"Crispinus",
"Crus",
"Curio",
"Cursor",
"Decula",
"Dentatus",
"Diadematus",
"Dives",
"Dolabella",
"Drusus",
"Eburnus",
"Etruscus",
"Falto",
"Fimbria",
"Flaccus",
"Flaminius",
"Florus",
"Frugi",
"Fundulus",
"Galili",
"Gallus",
"Geminus",
"Germanicus",
"Geta",
"Glabrio",
"Gracchus",
"Gurges",
"Hispallus",
"Hypsaeus",
"Isauricus",
"Labeo",
"Laenas",
"Laevinus",
"Lentulus",
"Lepidus",
"Libo",
"Licinius",
"Ligus",
"Livianus",
"Longinus",
"Longus",
"Lucanus",
"Lucullus",
"Lupus",
"Luscinus",
"Macedonicus",
"Magnus",
"Malleolus",
"Mancinus",
"Marcellus",
"Maso",
"Matho",
"Maximus",
"Megellus",
"Merula",
"Messalla",
"Metellus",
"Murena",
"Mus",
"Nasica",
"Nero",
"Nerva",
"Niger",
"Nobilior",
"Noctua",
"Octavianus",
"Orestes",
"Otho",
"Pacilus",
"Paetinus",
"Paetus",
"Pansa",
"Papus",
"Papus",
"Paterculus",
"Paullus",
"Pennus",
"Pera",
"Philippus",
"Philo",
"Pictor",
"Piso",
"Pius",
"Plautus",
"Pollio",
"Porcina",
"Pulcher",
"Pullus",
"Purpurio",
"Ravilla",
"Regulus",
"Rufinus",
"Rufus",
"Rullianus",
"Russus",
"Sabinus",
"Salinator",
"Saverrio",
"Scaevola",
"Scipio",
"Serapio",
"Serranus",
"Servilianus",
"Silanus",
"Sophus",
"Spurinus",
"Strabo",
"Sulla",
"Sura",
"Tamphilus",
"Tappulus",
"Thalna",
"Thermus",
"Torquatus",
"Tremulus",
"Tuditanus",
"Tullus",
"Turrinus",
"Varro",
"Varus",
"Verrucosus",
"Vitulus",
"Vulso",
"Gundrabur");

$Nachname = array(
"Acilius",
"Aebutius",
"Aedinius",
"Albanius",
"Albatius",
"Allectius",
"Amatius",
"Antius",
"Antonius",
"Arminius",
"Armenius",
"Arrius",
"Artorius",
"Asinius",
"Ateius",
"Atius",
"Atilius",
"Atrius",
"Attius",
"Aulus",
"Aurelius",
"Ausonius",
"Atronius",
"Avisius",
"Barrius",
"Blandius",
"Bruccius",
"Bruttius",
"Calatorius",
"Calidius",
"Calpurnius",
"Calventius",
"Camillius",
"Camilius",
"Camelius",
"Caprenius",
"Carius",
"Caristanius",
"Cispius",
"Claudius",
"Clodius",
"Clovius",
"Cluntius",
"Cominius",
"Cordius",
"Cornelius",
"Cosconius",
"Crispus",
"Curius",
"Curtius",
"Decumius",
"Desticius",
"Dexsius",
"Didius",
"Dillius",
"Domitius",
"Dossenius",
"Duccius",
"Duronius",
"Egnatius",
"Epidius",
"Equitius",
"Fabius",
"Fadius",
"Falerius",
"Favonius",
"Fenius",
"Festinius",
"Flaccus",
"Flavius",
"Flavinius",
"Flavonius",
"Floridius",
"Florius",
"Floronius",
"Fulcinius",
"Fulvius",
"Fundanus",
"Furius",
"Gabinius",
"Galerius",
"Gallus",
"Gavius",
"Gellius",
"Granius",
"Grattius",
"Gratidius",
"Helvetius",
"Helvius",
"Herennius",
"Herminius",
"Horatius",
"Hortensius",
"Hosidius",
"Hostilius",
"Inventius",
"Iulius",
"Iunius",
"Iustus",
"Iuventius",
"Laetonius",
"Lafrenius",
"Lampronius",
"Liburnius",
"Licinius",
"Ligustinius",
"Livius",
"Lollius",
"Longinius",
"Loreius",
"Lucius",
"Lucilius",
"Lusius",
"Macrinius",
"Maecilius",
"Maelius",
"Mallius",
"Mamilius",
"Manlius",
"Manilius",
"Marcius",
"Marius",
"Matius",
"Maximius",
"Memmius",
"Messienus",
"Metilius",
"Milonius",
"Minicius",
"Modius",
"Mucius",
"Munatius",
"Munius",
"Murrius",
"Minucius",
"Naevius",
"Nasennius",
"Nemetorius",
"Nepius",
"Nigidius",
"Nigilius",
"Nipius",
"Norbanus",
"Novius",
"Numerius",
"Olcinius",
"Oppius",
"Opsius",
"Oranius",
"Otacilius",
"Palpellius",
"Papinius",
"Papirius",
"Papius",
"Peltrasius",
"Pescennius",
"Petellius",
"Petilius",
"Petillius",
"Petronius",
"Pinarius",
"Piscius",
"Pisentius",
"Placidius",
"Plautius",
"Plinius",
"Plotius",
"Pollius",
"Pomponius",
"Pomptinus",
"Pontidius",
"Pontius",
"Popidius",
"Portius",
"Postumius",
"Paesentius",
"Publicius",
"Pupius",
"Quintilius",
"Quintius",
"Quirinius",
"Rabirius",
"Rufius",
"Rufrius",
"Rufus",
"Rusonius",
"Rutilius",
"Sabucius",
"Sallustius",
"Salonius",
"Salvius",
"Scribonius",
"Secundinius",
"Secundius",
"Seius",
"Sempronius",
"Sennius",
"Sentius",
"Septimius",
"Sepunius",
"Sepurcius",
"Sergius",
"Servilius",
"Sestius",
"Sextilius",
"Sextius",
"Sidonius",
"Silius",
"Sittius",
"Socellius",
"Sornatius",
"Spurius",
"Statius",
"Statlilius",
"Stertinius",
"Suedius",
"Sulpicius",
"Tadius",
"Talmudius",
"Tanicius",
"Tertinius",
"Tettidius",
"Tettienus",
"Tettius",
"Titiedius",
"Titius",
"Titinius",
"Trebatius",
"Trebellius",
"Treblanus",
"Tremellius",
"Tuccius",
"Tullius",
"Ulpius",
"Umbrenius",
"Umbrius",
"Urgulanius",
"Uulius",
"Vagennius",
"Vagionius",
"Vagnius",
"Valerius",
"Varius",
"Vassenius",
"Vatinius",
"Vedius",
"Velius",
"Veranius",
"Verecundius",
"Vergilius",
"Vesnius",
"Vesuvius",
"Vibenius",
"Vibidius",
"Victricius",
"Viducius",
"Vinicius",
"Vipsanius",
"Vipstanus",
"Viridius",
"Virius",
"Vitruvius",
"Volaginius",
"Volcatius",
"Volumnius",
"Volusenna",
"Volusenus",
"Volusius");

?>
